name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'

      # - uses: actions/setup-node@v2.4.0
      #   if: steps.check.outputs.changed == 'true'
      #   with:
      #     node-version: 14
      #     cache: 'yarn'

      # - name: Install Dependencies
      #   if: steps.check.outputs.changed == 'true'
      #   run: yarn --frozen-lockfile

      # - name: Build package
      #   if: steps.check.outputs.changed == 'true'
      #   run: yarn -s build
