name: Trunk

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [14.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - run: yarn -s build
      - run: yarn -s test
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@2512d2ac9130c439e045344eb6603a81f4b0f915 # tag=v2.1.0

        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3.2.0
        if: steps.check.outputs.changed == 'true'
        with:
          scope: '@renovatebot'
          node-version: 14
          cache: 'yarn'

      - name: Install Dependencies
        if: steps.check.outputs.changed == 'true'
        run: yarn --frozen-lockfile

      - name: Build package
        if: steps.check.outputs.changed == 'true'
        run: yarn -s build

      - name: Publish package to NPM
        if: steps.check.outputs.changed == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Node.js for GPR
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3.2.0
        with:
          scope: '@renovatebot'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Publish package to GPR
        if: steps.check.outputs.changed == 'true'
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
